"""Initial Migration

Revision ID: 0b6131bc360e
Revises: 211f2e2db58a
Create Date: 2022-07-23 23:06:34.962607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b6131bc360e'
down_revision = '211f2e2db58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor_info_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('donor_name1', sa.String(length=200), nullable=True),
    sa.Column('donor_name2', sa.String(length=200), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('pan_number', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=200), nullable=True),
    sa.Column('trs', sa.String(length=200), nullable=True),
    sa.Column('range', sa.Integer(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pan_number'),
    sa.UniqueConstraint('phone_number')
    )
    op.drop_table('donor_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('donor_name1', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('donor_name2', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('pan_number', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('trs', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('range', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='donor_info_pkey'),
    sa.UniqueConstraint('email', name='donor_info_email_key'),
    sa.UniqueConstraint('pan_number', name='donor_info_pan_number_key'),
    sa.UniqueConstraint('phone_number', name='donor_info_phone_number_key')
    )
    op.drop_table('donor_info_details')
    # ### end Alembic commands ###
