"""Initial Migration

Revision ID: 7d3e1e8aef5a
Revises: 
Create Date: 2022-07-22 18:41:07.723974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3e1e8aef5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donor_table', sa.Column('category', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donor_table', 'category')
    # ### end Alembic commands ###
