"""Initial migration

Revision ID: eb5b3695ce63
Revises: 7d3e1e8aef5a
Create Date: 2022-07-23 15:24:52.405536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5b3695ce63'
down_revision = '7d3e1e8aef5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('range')
    op.drop_table('category_table')
    op.add_column('donor_table', sa.Column('range', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donor_table', 'range')
    op.create_table('category_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_table_pkey')
    )
    op.create_table('range',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('range', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='range_pkey')
    )
    # ### end Alembic commands ###
